### ISSUE TITLE
i have an issue...

### ISSUE THREAD

**Issue by MOB-atheist** [LucasAlvaresA/netflix-clone#1]
<img src="https://i.pinimg.com/originals/d0/d9/1a/d0d91a5503388584c61ac7908cc0cc26.gif" width="100%"/>

**Comment by LucasAlvaresA** [comment]
Thanks for this issue my friend!!
<img src="https://gifdownload.net/wp-content/uploads/2019/01/dancing-loli-gif-2.gif"  width="100%" />
